name: Run Bot

on:
  workflow_dispatch: # Sirf manual run ke liye

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Chromium & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libnss3 libfontconfig1 libgbm1 libasound2 libatk-bridge2.0-0 libgtk-3-0

      - name: Build and Run Bot
        run: cargo run --release
